// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ginblog/internal/handler"
	"ginblog/internal/middleware"
	"ginblog/internal/repository"
	"ginblog/internal/server"
	"ginblog/internal/service"
	"ginblog/pkg/log"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger, jwt *middleware.JWT) (*gin.Engine, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger)
	db := repository.NewDb(viperViper)
	repositoryRepository := repository.NewRepository(logger, db)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	articleRepository := repository.NewArticleRepository(repositoryRepository)
	articleService := service.NewArticleService(serviceService, articleRepository)
	articleHandler := handler.NewArticleHandler(handlerHandler, articleService)
	categoryRepository := repository.NewCategoryRepository(repositoryRepository)
	categoryService := service.NewCategoryService(serviceService, categoryRepository)
	categoryHandler := handler.NewCategoryHandler(handlerHandler, categoryService)
	commentRepository := repository.NewCommentRepository(repositoryRepository)
	commentService := service.NewCommentService(serviceService, commentRepository)
	commentHandler := handler.NewCommentHandler(handlerHandler, commentService)
	profileRepository := repository.NewProfileRepository(repositoryRepository)
	profileService := service.NewProfileService(serviceService, profileRepository)
	profileHandler := handler.NewProfileHandler(handlerHandler, profileService)
	loginHandler := handler.NewLoginHandler(handlerHandler, viperViper, userService)
	engine := server.NewServerHTTP(logger, userHandler, articleHandler, categoryHandler, commentHandler, profileHandler, loginHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var RepositorySet = wire.NewSet(repository.NewDb, repository.NewRepository, repository.NewUserRepository, repository.NewArticleRepository, repository.NewCategoryRepository, repository.NewCommentRepository, repository.NewProfileRepository)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewArticleService, service.NewCategoryService, service.NewCommentService, service.NewProfileService)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewArticleHandler, handler.NewCategoryHandler, handler.NewCommentHandler, handler.NewProfileHandler, handler.NewLoginHandler)
